language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
branches:
  only:
    - master
    - token_ext_trait
script:
  - cargo test -- --test-threads=1
  - cargo test --example google
  - cargo test --example github
  - cargo test --doc
notifications:
  email:
    on_success: never
