language: rust
rust:
  - 1.34.0
  - stable
  - beta
  - nightly
sudo: false
cache: cargo
before_script:
  - cargo install --force cargo-audit
script:
  # Blocking reqwest using current reqwest
  - cargo test
  - cargo test --example google
  - cargo test --example github
  - cargo test --example msgraph
  - cargo test --all-features
  - cargo test --no-default-features --features "futures-03"
  # All features enabled
  - cargo test --all-features
  # Blocking reqwest using reqwest 0.9
  - cargo test --features reqwest --no-default-features
  # Futures 0.1 without reqwest
  - cargo test --features futures-01 --no-default-features
  # Futures 0.3 without reqwest 0.9 (but includes reqwest 0.10)
  - cargo test --features futures-03 --no-default-features
  # Futures 0.1 with reqwest 0.9
  - cargo test --features reqwest,futures-01 --no-default-features
  # Futures 0.3 with reqwest 0.9 (included by default)
  - cargo test --features futures-03
  - cargo audit
notifications:
  email:
    on_success: never
