[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "3.0.0-alpha.5"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"
edition = "2018"

[features]
default = ["reqwest"]
futures-01 = ["futures-0-1"]
futures-03 = ["futures-0-3", "async-std", "async-trait", "reqwest-0-10"]
reqwest = ["reqwest-0-9"]

[dependencies]
async-std = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
base64 = "0.10"
curl = { version = "0.4.0", optional = true }
failure = "0.1"
failure_derive = "0.1"
futures-0-1 = { version = "0.1", optional = true, package = "futures" }
futures-0-3 = { version = "0.3", optional = true, package = "futures" }
http = "0.1"
rand = "0.6"
reqwest-0-9 = { version = "0.9", optional = true, package = "reqwest" }
reqwest-0-10 = { version = "0.10.0-alpha.2", optional = true, features = ["blocking"], package = "reqwest" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.7"
url = "2.1"

[dev-dependencies]
tokio = "0.1"
